name: Publish npm package
on:
  push:
    tags:
      - '*'
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Get tag name
      id: tagName
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Replace version placeholder
      run: sh scripts/replace-next-version-tag.sh ${{ steps.tagName.outputs.tag }}
    - name: Install node packages
      run: npm install
    - name: Generate docs
      run: npm run docs
    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        token: '${{ secrets.ACCESS_TOKEN }}'
    - name: Add and Commit changes
      uses: EndBug/add-and-commit@v7.0.0
      with:
        add: '.'
        message: 'Prepare release'
        branch: master
  publish:
    needs: prepare-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag name
      id: tagName
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install node packages
      run: npm install
    - name: Set package version
      run: npm version ${{ steps.tagName.outputs.tag }}
    - name: Build index
      run: npm run cti
    - name: Build project
      run: npm run build
    - name: Run tests with coverage
      run: npm test
    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
